name: Deploy

on:
  push:
    branches:
      - 'master'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install EC2 Connect CLI
        run: |
          pip install ec2instanceconnectcli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-northeast-1

      - name: Deploy to EC2
        env:
          APP_NAME: ${{ env.APP_NAME }}
          GROUP_NAME: ${{ env.GROUP_NAME }}
        run: aws deploy create-deployment \
          --application-name $APP_NAME \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name $GROUP_NAME \
          --description "My GitHub deployment demo" \
          --github-location repository=$GITHUB_REPOSITORY,commitId=$GITHUB_SHA